from app.models.role import Role
from app.models.user import User
from app.models.student import Student
from app.models.lecturer import Lecturer
from app.models.class_ import Class
from app.models.class_assignment import ClassAssignment
from app.models.attendance import Attendance
from app.models.grade import Grade
from app.models.ticket import Ticket
from app.models.report import Report
from app.models.notification import Notification
from app.models.lecturers_attendance import LecturerAttendanceStatus
